/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 robo_3d.glb -t 
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import VideoPlane from './EyeTrackMesh'

type ActionName = 'animation_0'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    FACE: THREE.Mesh
    SCHEME: THREE.Mesh
    C: THREE.Mesh
    pipes_Torus1: THREE.Mesh
    ears_Cylinder001: THREE.Mesh
    ears_Cylinder: THREE.Mesh
    top: THREE.Mesh
    bottom: THREE.Mesh
    pipes_Torus: THREE.Mesh
    SCREEN: THREE.Mesh
    stroke: THREE.Mesh
    hand_L_bottom: THREE.Mesh
    hand_L_top: THREE.Mesh
    hand_R_fingers: THREE.Mesh
    hand_R_thumb: THREE.Mesh
    hand_R_bottom: THREE.Mesh
    ['hand_R-top']: THREE.Mesh
    dots: THREE.Mesh
    pipes_body: THREE.Mesh
    body: THREE.Mesh
    leg_L_1: THREE.Mesh
    ler_R_1: THREE.Mesh
    TOUCH: THREE.Mesh
    pod: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export function Robo_3d(props: any) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, animations } = useGLTF('/robo_3d.glb') as GLTFResult
  const { actions } = useAnimations(animations, group);

  const head = useRef<THREE.Group>(null);
  const hand_left = useRef<THREE.Group>(null);
  const hand_right = useRef<THREE.Group>(null);

  useEffect(() => {
    if (actions.animation_0) {
      actions.animation_0.play();
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group>
          <group name="pose_hero" position={[9.388, 208.5, -5.173]} rotation={[-0.092, -0.076, -0.027]}>
            <group name="mixamorigSpine" position={[0, 22.088, -1.514]} rotation={[-0.027, 0.002, 0.01]}>
              <group name="mixamorigSpine1" position={[0, 25.83, 0]} rotation={[0.082, 0.004, 0.022]}>
                <group name="mixamorigSpine2" position={[0, 29.52, 0]} rotation={[0.082, -0.006, 0.023]}>
                  <group name="mixamorigNeck" position={[0, 33.209, 0]} rotation={[-0.271, -0.001, -0.007]}>
                    <group ref={head} name="mixamorigHead" position={[0, 85.057, -3.146]} rotation={[0.235, 0.046, -0.019]}>
                      {/* <mesh name="FACE" geometry={nodes.FACE.geometry} material={nodes.FACE.material} position={[-19.12, 118.687, 142.834]} rotation={[0.013, -0.082, 0.015]} scale={75} /> */}
                      <VideoPlane/>
                      <mesh name="SCHEME" geometry={nodes.SCHEME.geometry} material={nodes.SCHEME.material} position={[-7.836, 189.076, -11.166]} rotation={[0.013, -0.082, -3.126]} scale={129.61} />
                      <mesh name="C" geometry={nodes.C.geometry} material={nodes.C.material} position={[-16.585, 120.243, 121.036]} rotation={[0.013, -0.082, 0.015]} scale={135.705} />
                      <mesh name="pipes_Torus1" geometry={nodes.pipes_Torus1.geometry} material={nodes.pipes_Torus1.material} position={[138.502, 70.365, 5.658]} rotation={[0.013, -0.082, 0.015]} scale={27.197} />
                      <mesh name="ears_Cylinder001" geometry={nodes.ears_Cylinder001.geometry} material={nodes.ears_Cylinder001.material} position={[145.065, 122.467, 6.243]} rotation={[0.013, -0.082, 0.015]} scale={37.399} />
                      <mesh name="ears_Cylinder" geometry={nodes.ears_Cylinder.geometry} material={nodes.ears_Cylinder.material} position={[-158.517, 118.11, -18.724]} rotation={[-3.129, 0.082, 3.126]} scale={37.399} />
                      <mesh name="top" geometry={nodes.top.geometry} material={nodes.top.material} position={[-7.714, 193.205, -9.849]} rotation={[0.013, -0.082, -3.126]} scale={136.979} />
                      <mesh name="bottom" geometry={nodes.bottom.geometry} material={nodes.bottom.material} position={[-5.467, 46.292, -11.541]} rotation={[0.013, -0.082, 0.015]} scale={136.975} />
                      <mesh name="pipes_Torus" geometry={nodes.pipes_Torus.geometry} material={nodes.pipes_Torus.material} position={[-150.502, 66.217, -18.128]} rotation={[-3.129, 0.082, 3.126]} scale={27.197} />
                      <mesh name="SCREEN" geometry={nodes.SCREEN.geometry} material={nodes.SCREEN.material} position={[-17.722, 120.186, 123.339]} rotation={[0.013, -0.082, 0.015]} scale={89.724} />
                      <mesh name="stroke" geometry={nodes.stroke.geometry} material={nodes.stroke.material} position={[-17.235, 120.68, 128.598]} rotation={[-0.015, 0.021, -0.005]} scale={108.644} />
                    </group>
                  </group>
                  <group name="mixamorigLeftShoulder" position={[46.544, 23.183, 14.611]} rotation={[1.742, -0.331, -1.726]}>
                    <group ref={hand_right} name="mixamorigLeftArm" position={[0, 94.502, 0]} rotation={[0.885, 0.129, 0.008]}>
                      <group name="mixamorigLeftForeArm" position={[0, 66.462, 0]} rotation={[0.051, -0.043, 0.395]}>
                        <group name="mixamorigLeftHand" position={[0, 97.553, 0]} rotation={[0.684, 1.196, -0.956]}>
                          <group name="mixamorigLeftHandThumb1" position={[-1.498, 5.829, -9.875]} rotation={[-0.327, 0.244, 0.453]}>
                            <group name="mixamorigLeftHandThumb2" position={[-0.369, 9.244, 0]} rotation={[0.076, -0.057, 0.106]}>
                              <group name="mixamorigLeftHandThumb3" position={[1.671, 21.742, 0]} rotation={[0, 0.001, -0.148]} />
                            </group>
                          </group>
                          <group name="mixamorigLeftHandIndex1" position={[0, 17.048, 0]} rotation={[0.11, 0.023, 0.671]}>
                            <group name="mixamorigLeftHandIndex2" position={[0.159, 21.994, 0]} rotation={[0.013, 0.067, 0.571]}>
                              <group name="mixamorigLeftHandIndex3" position={[0.173, 23.019, 0]} rotation={[0, 0.001, -0.031]} />
                            </group>
                          </group>
                        </group>
                        <mesh name="hand_L_bottom" geometry={nodes.hand_L_bottom.geometry} material={nodes.hand_L_bottom.material} position={[-12.086, 78.288, 1.395]} rotation={[-2.717, -0.948, -1.148]} scale={102.043} />
                      </group>
                      <mesh name="hand_L_top" geometry={nodes.hand_L_top.geometry} material={nodes.hand_L_top.material} position={[-5.334, 5.384, 19.885]} rotation={[2.504, -0.826, -1.791]} scale={53.167} />
                    </group>
                  </group>
                  <group name="mixamorigRightShoulder" position={[-45.649, 20.935, -0.911]} rotation={[1.8, 0.216, 1.437]}>
                    <group ref={hand_left} name="mixamorigRightArm" position={[0, 94.502, 0]} rotation={[0.892, -0.24, -0.175]}>
                      <group name="mixamorigRightForeArm" position={[0, 66.46, 0]} rotation={[0.059, 0.047, -0.551]}>
                        <group name="mixamorigRightHand" position={[0, 97.291, 0]} rotation={[-0.711, 1.128, 0.487]}>
                          <group name="mixamorigRightHandThumb1" position={[0.067, 6.542, 9.787]} rotation={[0.562, -0.097, 0.486]}>
                            <group name="mixamorigRightHandThumb2" position={[0.463, 9.407, 0]} rotation={[-0.092, 0.053, 0.066]}>
                              <group name="mixamorigRightHandThumb3" position={[2.582, 21.945, 0]} rotation={[0.001, 0.005, -0.281]} />
                            </group>
                            <mesh name="hand_R_fingers" geometry={nodes.hand_R_fingers.geometry} material={nodes.hand_R_fingers.material} position={[27.987, 12.428, -34.764]} rotation={[-0.696, 0.444, -1.58]} scale={27.086} />
                          </group>
                          <group name="mixamorigRightHandIndex1" position={[-1.935, 19.583, -4.158]} rotation={[-0.064, 0.029, 0.485]}>
                            <group name="mixamorigRightHandIndex2" position={[0.249, 22.586, 0]} rotation={[0.095, -0.033, 0.703]}>
                              <group name="mixamorigRightHandIndex3" position={[0.171, 21.536, 0]} rotation={[0, -0.001, -0.036]} />
                            </group>
                            <mesh name="hand_R_thumb" geometry={nodes.hand_R_thumb.geometry} material={nodes.hand_R_thumb.material} position={[31.639, 1.209, 15.435]} rotation={[-1.387, -0.146, -2.54]} scale={22.769} />
                          </group>
                        </group>
                        <mesh name="hand_R_bottom" geometry={nodes.hand_R_bottom.geometry} material={nodes.hand_R_bottom.material} position={[0.85, 51.894, -12.19]} rotation={[-2.616, 0.428, 1.214]} scale={65.949} />
                      </group>
                      <mesh name="hand_R-top" geometry={nodes['hand_R-top'].geometry} material={nodes['hand_R-top'].material} position={[-12.448, 11.212, 15.316]} rotation={[2.938, 0.826, 1.539]} scale={47.653} />
                    </group>
                  </group>
                </group>
                <mesh name="dots" geometry={nodes.dots.geometry} material={nodes.dots.material} position={[21.47, 65.056, 67.012]} rotation={[0.042, 0.074, -0.012]} scale={22.492} />
                <mesh name="pipes_body" geometry={nodes.pipes_body.geometry} material={nodes.pipes_body.material} position={[-15.199, -27.639, 62.175]} rotation={[-0.053, -0.06, 0.018]} scale={64.771} />
                <mesh name="body" geometry={nodes.body.geometry} material={nodes.body.material} position={[-12.181, 7.677, -6.063]} rotation={[0.042, 0.074, -0.012]} scale={131.843} />
              </group>
            </group>
            <group name="mixamorigRightUpLeg" position={[-47.366, -12.357, -0.685]} rotation={[0.047, -0.072, -3.133]}>
              <group name="mixamorigRightLeg" position={[0, 84.62, 0]} rotation={[-0.227, 0.001, -0.001]}>
                <group name="mixamorigRightFoot" position={[0, 96.483, 0]} rotation={[1.281, 0.507, -0.855]}>
                  <group name="mixamorigRightToeBase" position={[0, 32.549, 0]} rotation={[0.694, 0.155, -0.127]} />
                </group>
              </group>
            </group>
          </group>
          <group name="leg_L" position={[10.436, 1.938, 1.714]} rotation={[-0.05, -0.014, 0.012]}>
            <mesh name="leg_L_1" geometry={nodes.leg_L_1.geometry} material={nodes.leg_L_1.material} position={[45.369, 83.289, 4.232]} scale={86.548} />
          </group>
          <group name="ler_R" position={[-5.26, 3.611, -3.164]} rotation={[-0.006, -0.014, 0.012]}>
            <mesh name="ler_R_1" geometry={nodes.ler_R_1.geometry} material={nodes.ler_R_1.material} position={[-45.412, 83.177, -2.104]} scale={86.617} />
          </group>
          {/* <mesh name="TOUCH" geometry={nodes.TOUCH.geometry} material={nodes.TOUCH.material} position={[-138.103, 160.27, 164.633]} scale={75} /> */}
          <mesh name="pod" geometry={nodes.pod.geometry} material={nodes.pod.material} position={[0, -119.866, -8.897]} scale={121.2} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/robo_3d.glb')
